package com.deceval.comercial.pagares.entidad.pagares;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-02-21T09:52:37.890-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.deceval.com/comercial/pagares/entidad/Pagares", name = "PagaresPortType")
@XmlSeeAlso({com.deceval.comunes.modelos.xsd.errores.ObjectFactory.class, com.deceval.comunes.modelos.xsd.encabezados.ObjectFactory.class, com.deceval.comercial.modelos.xsd.pagares.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PagaresPortType {

    @WebResult(name = "ResultadoCreacion", targetNamespace = "http://www.deceval.com/comercial/modelos/xsd/Pagares", partName = "ResultadoCreacion")
    @WebMethod(operationName = "Crear", action = "http://www.deceval.com/comercial/pagares/entidad/Pagares/crear")
    public com.deceval.comercial.modelos.xsd.pagares.ResultadoCreacionType crear(
        @WebParam(partName = "PagareCrear", name = "Pagares", targetNamespace = "http://www.deceval.com/comercial/modelos/xsd/Pagares")
        com.deceval.comercial.modelos.xsd.pagares.ListaPagaresType pagareCrear
    ) throws MensajeError;
}
