
package com.deceval.comercial.pagares.entidad.pagares;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-02-21T09:52:37.865-05:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "ErrorGenerico", targetNamespace = "http://www.deceval.com/comunes/modelos/xsd/Errores")
public class MensajeError extends Exception {
    
    private com.deceval.comunes.modelos.xsd.errores.ErrorGenericoType errorGenerico;

    public MensajeError() {
        super();
    }
    
    public MensajeError(String message) {
        super(message);
    }
    
    public MensajeError(String message, Throwable cause) {
        super(message, cause);
    }

    public MensajeError(String message, com.deceval.comunes.modelos.xsd.errores.ErrorGenericoType errorGenerico) {
        super(message);
        this.errorGenerico = errorGenerico;
    }

    public MensajeError(String message, com.deceval.comunes.modelos.xsd.errores.ErrorGenericoType errorGenerico, Throwable cause) {
        super(message, cause);
        this.errorGenerico = errorGenerico;
    }

    public com.deceval.comunes.modelos.xsd.errores.ErrorGenericoType getFaultInfo() {
        return this.errorGenerico;
    }
}
