package com.deceval.comercial.pagares.entidad.pagares;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-02-21T09:52:37.978-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "Pagares", 
                  wsdlLocation = "file:/home/anarvaez/workspace/demo.deceval2/wsdl/Pagare.wsdl",
                  targetNamespace = "http://www.deceval.com/comercial/pagares/entidad/Pagares") 
public class Pagares extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.deceval.com/comercial/pagares/entidad/Pagares", "Pagares");
    public final static QName PagaresPort = new QName("http://www.deceval.com/comercial/pagares/entidad/Pagares", "PagaresPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/anarvaez/workspace/demo.deceval2/wsdl/Pagare.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Pagares.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/anarvaez/workspace/demo.deceval2/wsdl/Pagare.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Pagares(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Pagares(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Pagares() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Pagares(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Pagares(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Pagares(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PagaresPortType
     */
    @WebEndpoint(name = "PagaresPort")
    public PagaresPortType getPagaresPort() {
        return super.getPort(PagaresPort, PagaresPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagaresPortType
     */
    @WebEndpoint(name = "PagaresPort")
    public PagaresPortType getPagaresPort(WebServiceFeature... features) {
        return super.getPort(PagaresPort, PagaresPortType.class, features);
    }

}
