package co.com.deceval.tecnologia.auditoria.util.auditoria;

import javax.xml.ws.WebFault;
import com.deceval.comunes.modelos.xsd.errores.ErrorGenericoType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 *
 */
@WebFault(name = "ErrorGenerico", targetNamespace = "http://www.deceval.com/comunes/modelos/xsd/Errores")
public class MensajeError
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private ErrorGenericoType faultInfo;

    /**
     *
     * @param message
     * @param faultInfo
     */
    public MensajeError(String message, ErrorGenericoType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MensajeError(String message, ErrorGenericoType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return returns fault bean:
     * com.deceval.comunes.modelos.xsd.errores.ErrorGenericoType
     */
    public ErrorGenericoType getFaultInfo() {
        return faultInfo;
    }
}
