package co.com.deceval.tecnologia.auditoria.util.auditoria;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(name = "Auditoria", targetNamespace = "http://www.deceval.com.co/tecnologia/auditoria/util/Auditoria", wsdlLocation = "file:/D:/NetBeans/ServicioAuditoriaDeceval/src/java/Auditoria.wsdl")
public class Auditoria
        extends Service {

    private final static URL AUDITORIA_WSDL_LOCATION;
    private final static WebServiceException AUDITORIA_EXCEPTION;
    private final static QName AUDITORIA_QNAME = new QName("http://www.deceval.com.co/tecnologia/auditoria/util/Auditoria", "Auditoria");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/NetBeans/ServicioAuditoriaDeceval/src/java/Auditoria.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUDITORIA_WSDL_LOCATION = url;
        AUDITORIA_EXCEPTION = e;
    }

    public Auditoria() {
        super(__getWsdlLocation(), AUDITORIA_QNAME);
    }

    public Auditoria(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUDITORIA_QNAME, features);
    }

    public Auditoria(URL wsdlLocation) {
        super(wsdlLocation, AUDITORIA_QNAME);
    }

    public Auditoria(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUDITORIA_QNAME, features);
    }

    public Auditoria(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Auditoria(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns AuditoriaPortType
     */
    @WebEndpoint(name = "AuditoriaPort")
    public AuditoriaPortType getAuditoriaPort() {
        return super.getPort(new QName("http://www.deceval.com.co/tecnologia/auditoria/util/Auditoria", "AuditoriaPort"), AuditoriaPortType.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in      * the <code>features</code> parameter will have their default
     * values.
     * @return returns AuditoriaPortType
     */
    @WebEndpoint(name = "AuditoriaPort")
    public AuditoriaPortType getAuditoriaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.deceval.com.co/tecnologia/auditoria/util/Auditoria", "AuditoriaPort"), AuditoriaPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUDITORIA_EXCEPTION != null) {
            throw AUDITORIA_EXCEPTION;
        }
        return AUDITORIA_WSDL_LOCATION;
    }
}
