package com.deceval.tecnologia.usuarios.utilidad.validarusuario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-02-24T09:39:06.442-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.deceval.com/tecnologia/usuarios/utilidad/ValidarUsuario", name = "ValidarUsuarioPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ValidarUsuarioPortType {

    @WebResult(name = "UsuarioValidarResponse", targetNamespace = "http://www.deceval.com/tecnologia/usuarios/utilidad/ValidarUsuario", partName = "parameters")
    @WebMethod(operationName = "Validar", action = "Validar")
    public UsuarioValidarResponse validar(
        @WebParam(partName = "parameters", name = "UsuarioValidar", targetNamespace = "http://www.deceval.com/tecnologia/usuarios/utilidad/ValidarUsuario")
        UsuarioValidar parameters
    );
}
