package com.deceval.tecnologia.usuarios.utilidad.validarusuario;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-02-24T09:39:06.477-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ValidarUsuario", 
                  wsdlLocation = "file:/home/anarvaez/workspace/demo.deceval2/wsdl/validarUsuario.wsdl",
                  targetNamespace = "http://www.deceval.com/tecnologia/usuarios/utilidad/ValidarUsuario") 
public class ValidarUsuario extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.deceval.com/tecnologia/usuarios/utilidad/ValidarUsuario", "ValidarUsuario");
    public final static QName ValidarUsuarioPort = new QName("http://www.deceval.com/tecnologia/usuarios/utilidad/ValidarUsuario", "ValidarUsuarioPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/anarvaez/workspace/demo.deceval2/wsdl/validarUsuario.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ValidarUsuario.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/anarvaez/workspace/demo.deceval2/wsdl/validarUsuario.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ValidarUsuario(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ValidarUsuario(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidarUsuario() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ValidarUsuario(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ValidarUsuario(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ValidarUsuario(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ValidarUsuarioPortType
     */
    @WebEndpoint(name = "ValidarUsuarioPort")
    public ValidarUsuarioPortType getValidarUsuarioPort() {
        return super.getPort(ValidarUsuarioPort, ValidarUsuarioPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidarUsuarioPortType
     */
    @WebEndpoint(name = "ValidarUsuarioPort")
    public ValidarUsuarioPortType getValidarUsuarioPort(WebServiceFeature... features) {
        return super.getPort(ValidarUsuarioPort, ValidarUsuarioPortType.class, features);
    }

}
